language: bash

# Use docker service
services: docker

# Install dependencies
install:
  - echo "Install dependencies"

# Tasks and scripts to run before tests
before_script:
  - echo "Prepare to run test suites"

# Run tests suites
script:
  - echo "run all the tests"

# After tests
after_script:
  - docker images

notifications:
  email: false